/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c78f8fe7-1d93-4ee7-9c49-315fc638a542",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_nxfpsYhVu",
    "aws_user_pools_web_client_id": "5f65eirn0hejk1r37ej7h4o3n7",
    "oauth": {
        "domain": "snappetd98aa418-d98aa418-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://d3jc204md9jxdy.cloudfront.net/dashboard/",
        "redirectSignOut": "https://d3jc204md9jxdy.cloudfront.net/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "snappet-20230913190833-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d3jc204md9jxdy.cloudfront.net"
};


export default awsmobile;
